baseURL = "https://tehnoloskidorucak.io/"
languageCode = "sr-RS"
title = "Tehnološki Doručak"
description = "Mesečno okupljanje sa ciljem brze razmene preduzetničkih ideja u prijatnoj atmosferi prve jutarnje kafe."
