baseURL = "https://tehnoloskidorucak.io/"
languageCode = "sr-RS"
title = "Tehnološki doručak"

[params]
  description = "Mesečno okupljanje sa ciljem brze razmene preduzetničkih ideja u prijatnoj atmosferi prve jutarnje kafe."
